export const SET_DATA_TS = 'SET_DATA_TS';
export const RESET_DATA_TS = 'RESET_DATA_TS';

export const UPDATE_APP_NAME = 'UPDATE_APP_NAME';
export const UPDATE_TEST_MODIFY_STATE = 'UPDATE_TEST_MODIFY_STATE';
