module.exports = {
    /** [客户端] 语言ID */
    LOCALEID: '__KOOT_LOCALEID__',

    STORE: '__KOOT_STORE__',
    HISTORY: '__KOOT_HISTORY__',
    CACHE: '__KOOT_CACHE__',
    REDUXSTATE: '__REDUX_STATE__',
    SSRSTATE: '__KOOT_SSR_STATE__',
    SPALOCALEFILEMAP: '__KOOT_SPA_LOCALE_FILE_MAP__',

    DEV_NATIVE_CONSOLE: '__KOOT_DEV_NATIVE_CONSOLE__',
};
