module.exports = {
    KOOT_BUILD_START_TIME: 'KOOT_BUILD_START_TIME',
    KOOT_DEV_START_TIME: 'KOOT_DEV_START_TIME',
    KOOT_REACT_RUNTIME: 'KOOT_REACT_RUNTIME',
    KOOT_CLIENT_PUBLIC_PATH: 'KOOT_CLIENT_PUBLIC_PATH',
};
