export const CHANGE_LANGUAGE = '@@KOOT@@CHANGE_LANGUAGE'
export const GET_ORIGIN_URL = '@@KOOT@@GET_ORIGIN_URL'
export const TELL_CLIENT_URL = '@@KOOT@@TELL_CLIENT_URL'

export default {
    CHANGE_LANGUAGE,
    GET_ORIGIN_URL,
    TELL_CLIENT_URL,
}
