module.exports = {
    REACT_REPLACE_MEMO_IN_DEV_DEFAULT_INDENTIFIER: Symbol(
        '__KOOT_BABEL_PLUGIN_REACT_REPLACE_MEMO_IN_DEV_DEFAULT_INDENTIFIER_KOOT__'
    ),
    REACT_REPLACE_MEMO_IN_DEV_MEMO_LOCAL_INDENTIFIER: Symbol(
        '__KOOT_BABEL_PLUGIN_REACT_REPLACE_MEMO_IN_DEV_MEMO_LOCAL_INDENTIFIER_KOOT__'
    ),
};
